source 'http://rubygems.org'
source 'http://gemcutter.org'

gem 'rails', '3.0.9'
gem 'mysql'
gem 'hpricot'
gem 'ruby_parser'
gem 'devise'
gem 'haml'
gem 'haml-rails'
gem 'jquery-rails'
gem 'awesome_print'
gem 'mongo'
gem 'bson_ext'
gem 'easy_roles'
gem 'gemcutter'
gem "autotest"
gem 'factory_girl_rails'
gem "rspec-rails"
gem 'awesome_nested_set', :git => 'git://github.com/galetahub/awesome_nested_set.git'
gem 'awesome_print'
gem 'calendar_date_select'