require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe OwnedCarsController do

  def mock_owned_car(stubs={})
    @mock_owned_car ||= mock_model(OwnedCar, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all owned_cars as @owned_cars" do
      OwnedCar.stub(:all) { [mock_owned_car] }
      get :index
      assigns(:owned_cars).should eq([mock_owned_car])
    end
  end

  describe "GET show" do
    it "assigns the requested owned_car as @owned_car" do
      OwnedCar.stub(:find).with("37") { mock_owned_car }
      get :show, :id => "37"
      assigns(:owned_car).should be(mock_owned_car)
    end
  end

  describe "GET new" do
    it "assigns a new owned_car as @owned_car" do
      OwnedCar.stub(:new) { mock_owned_car }
      get :new
      assigns(:owned_car).should be(mock_owned_car)
    end
  end

  describe "GET edit" do
    it "assigns the requested owned_car as @owned_car" do
      OwnedCar.stub(:find).with("37") { mock_owned_car }
      get :edit, :id => "37"
      assigns(:owned_car).should be(mock_owned_car)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created owned_car as @owned_car" do
        OwnedCar.stub(:new).with({'these' => 'params'}) { mock_owned_car(:save => true) }
        post :create, :owned_car => {'these' => 'params'}
        assigns(:owned_car).should be(mock_owned_car)
      end

      it "redirects to the created owned_car" do
        OwnedCar.stub(:new) { mock_owned_car(:save => true) }
        post :create, :owned_car => {}
        response.should redirect_to(owned_car_url(mock_owned_car))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved owned_car as @owned_car" do
        OwnedCar.stub(:new).with({'these' => 'params'}) { mock_owned_car(:save => false) }
        post :create, :owned_car => {'these' => 'params'}
        assigns(:owned_car).should be(mock_owned_car)
      end

      it "re-renders the 'new' template" do
        OwnedCar.stub(:new) { mock_owned_car(:save => false) }
        post :create, :owned_car => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested owned_car" do
        OwnedCar.stub(:find).with("37") { mock_owned_car }
        mock_owned_car.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :owned_car => {'these' => 'params'}
      end

      it "assigns the requested owned_car as @owned_car" do
        OwnedCar.stub(:find) { mock_owned_car(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:owned_car).should be(mock_owned_car)
      end

      it "redirects to the owned_car" do
        OwnedCar.stub(:find) { mock_owned_car(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(owned_car_url(mock_owned_car))
      end
    end

    describe "with invalid params" do
      it "assigns the owned_car as @owned_car" do
        OwnedCar.stub(:find) { mock_owned_car(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:owned_car).should be(mock_owned_car)
      end

      it "re-renders the 'edit' template" do
        OwnedCar.stub(:find) { mock_owned_car(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested owned_car" do
      OwnedCar.stub(:find).with("37") { mock_owned_car }
      mock_owned_car.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the owned_cars list" do
      OwnedCar.stub(:find) { mock_owned_car }
      delete :destroy, :id => "1"
      response.should redirect_to(owned_cars_url)
    end
  end

end
