require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SettingTypesController do

  def mock_setting_type(stubs={})
    @mock_setting_type ||= mock_model(SettingType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all setting_types as @setting_types" do
      SettingType.stub(:all) { [mock_setting_type] }
      get :index
      assigns(:setting_types).should eq([mock_setting_type])
    end
  end

  describe "GET show" do
    it "assigns the requested setting_type as @setting_type" do
      SettingType.stub(:find).with("37") { mock_setting_type }
      get :show, :id => "37"
      assigns(:setting_type).should be(mock_setting_type)
    end
  end

  describe "GET new" do
    it "assigns a new setting_type as @setting_type" do
      SettingType.stub(:new) { mock_setting_type }
      get :new
      assigns(:setting_type).should be(mock_setting_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested setting_type as @setting_type" do
      SettingType.stub(:find).with("37") { mock_setting_type }
      get :edit, :id => "37"
      assigns(:setting_type).should be(mock_setting_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created setting_type as @setting_type" do
        SettingType.stub(:new).with({'these' => 'params'}) { mock_setting_type(:save => true) }
        post :create, :setting_type => {'these' => 'params'}
        assigns(:setting_type).should be(mock_setting_type)
      end

      it "redirects to the created setting_type" do
        SettingType.stub(:new) { mock_setting_type(:save => true) }
        post :create, :setting_type => {}
        response.should redirect_to(setting_type_url(mock_setting_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved setting_type as @setting_type" do
        SettingType.stub(:new).with({'these' => 'params'}) { mock_setting_type(:save => false) }
        post :create, :setting_type => {'these' => 'params'}
        assigns(:setting_type).should be(mock_setting_type)
      end

      it "re-renders the 'new' template" do
        SettingType.stub(:new) { mock_setting_type(:save => false) }
        post :create, :setting_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested setting_type" do
        SettingType.stub(:find).with("37") { mock_setting_type }
        mock_setting_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :setting_type => {'these' => 'params'}
      end

      it "assigns the requested setting_type as @setting_type" do
        SettingType.stub(:find) { mock_setting_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:setting_type).should be(mock_setting_type)
      end

      it "redirects to the setting_type" do
        SettingType.stub(:find) { mock_setting_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(setting_type_url(mock_setting_type))
      end
    end

    describe "with invalid params" do
      it "assigns the setting_type as @setting_type" do
        SettingType.stub(:find) { mock_setting_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:setting_type).should be(mock_setting_type)
      end

      it "re-renders the 'edit' template" do
        SettingType.stub(:find) { mock_setting_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested setting_type" do
      SettingType.stub(:find).with("37") { mock_setting_type }
      mock_setting_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the setting_types list" do
      SettingType.stub(:find) { mock_setting_type }
      delete :destroy, :id => "1"
      response.should redirect_to(setting_types_url)
    end
  end

end
