require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SetupGroupsController do

  def mock_setup_group(stubs={})
    @mock_setup_group ||= mock_model(SetupGroup, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all setup_groups as @setup_groups" do
      SetupGroup.stub(:all) { [mock_setup_group] }
      get :index
      assigns(:setup_groups).should eq([mock_setup_group])
    end
  end

  describe "GET show" do
    it "assigns the requested setup_group as @setup_group" do
      SetupGroup.stub(:find).with("37") { mock_setup_group }
      get :show, :id => "37"
      assigns(:setup_group).should be(mock_setup_group)
    end
  end

  describe "GET new" do
    it "assigns a new setup_group as @setup_group" do
      SetupGroup.stub(:new) { mock_setup_group }
      get :new
      assigns(:setup_group).should be(mock_setup_group)
    end
  end

  describe "GET edit" do
    it "assigns the requested setup_group as @setup_group" do
      SetupGroup.stub(:find).with("37") { mock_setup_group }
      get :edit, :id => "37"
      assigns(:setup_group).should be(mock_setup_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created setup_group as @setup_group" do
        SetupGroup.stub(:new).with({'these' => 'params'}) { mock_setup_group(:save => true) }
        post :create, :setup_group => {'these' => 'params'}
        assigns(:setup_group).should be(mock_setup_group)
      end

      it "redirects to the created setup_group" do
        SetupGroup.stub(:new) { mock_setup_group(:save => true) }
        post :create, :setup_group => {}
        response.should redirect_to(setup_group_url(mock_setup_group))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved setup_group as @setup_group" do
        SetupGroup.stub(:new).with({'these' => 'params'}) { mock_setup_group(:save => false) }
        post :create, :setup_group => {'these' => 'params'}
        assigns(:setup_group).should be(mock_setup_group)
      end

      it "re-renders the 'new' template" do
        SetupGroup.stub(:new) { mock_setup_group(:save => false) }
        post :create, :setup_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested setup_group" do
        SetupGroup.stub(:find).with("37") { mock_setup_group }
        mock_setup_group.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :setup_group => {'these' => 'params'}
      end

      it "assigns the requested setup_group as @setup_group" do
        SetupGroup.stub(:find) { mock_setup_group(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:setup_group).should be(mock_setup_group)
      end

      it "redirects to the setup_group" do
        SetupGroup.stub(:find) { mock_setup_group(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(setup_group_url(mock_setup_group))
      end
    end

    describe "with invalid params" do
      it "assigns the setup_group as @setup_group" do
        SetupGroup.stub(:find) { mock_setup_group(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:setup_group).should be(mock_setup_group)
      end

      it "re-renders the 'edit' template" do
        SetupGroup.stub(:find) { mock_setup_group(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested setup_group" do
      SetupGroup.stub(:find).with("37") { mock_setup_group }
      mock_setup_group.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the setup_groups list" do
      SetupGroup.stub(:find) { mock_setup_group }
      delete :destroy, :id => "1"
      response.should redirect_to(setup_groups_url)
    end
  end

end
