require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TrackTypesController do

  def mock_track_type(stubs={})
    @mock_track_type ||= mock_model(TrackType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all track_types as @track_types" do
      TrackType.stub(:all) { [mock_track_type] }
      get :index
      assigns(:track_types).should eq([mock_track_type])
    end
  end

  describe "GET show" do
    it "assigns the requested track_type as @track_type" do
      TrackType.stub(:find).with("37") { mock_track_type }
      get :show, :id => "37"
      assigns(:track_type).should be(mock_track_type)
    end
  end

  describe "GET new" do
    it "assigns a new track_type as @track_type" do
      TrackType.stub(:new) { mock_track_type }
      get :new
      assigns(:track_type).should be(mock_track_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested track_type as @track_type" do
      TrackType.stub(:find).with("37") { mock_track_type }
      get :edit, :id => "37"
      assigns(:track_type).should be(mock_track_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created track_type as @track_type" do
        TrackType.stub(:new).with({'these' => 'params'}) { mock_track_type(:save => true) }
        post :create, :track_type => {'these' => 'params'}
        assigns(:track_type).should be(mock_track_type)
      end

      it "redirects to the created track_type" do
        TrackType.stub(:new) { mock_track_type(:save => true) }
        post :create, :track_type => {}
        response.should redirect_to(track_type_url(mock_track_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved track_type as @track_type" do
        TrackType.stub(:new).with({'these' => 'params'}) { mock_track_type(:save => false) }
        post :create, :track_type => {'these' => 'params'}
        assigns(:track_type).should be(mock_track_type)
      end

      it "re-renders the 'new' template" do
        TrackType.stub(:new) { mock_track_type(:save => false) }
        post :create, :track_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested track_type" do
        TrackType.stub(:find).with("37") { mock_track_type }
        mock_track_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :track_type => {'these' => 'params'}
      end

      it "assigns the requested track_type as @track_type" do
        TrackType.stub(:find) { mock_track_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:track_type).should be(mock_track_type)
      end

      it "redirects to the track_type" do
        TrackType.stub(:find) { mock_track_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(track_type_url(mock_track_type))
      end
    end

    describe "with invalid params" do
      it "assigns the track_type as @track_type" do
        TrackType.stub(:find) { mock_track_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:track_type).should be(mock_track_type)
      end

      it "re-renders the 'edit' template" do
        TrackType.stub(:find) { mock_track_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested track_type" do
      TrackType.stub(:find).with("37") { mock_track_type }
      mock_track_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the track_types list" do
      TrackType.stub(:find) { mock_track_type }
      delete :destroy, :id => "1"
      response.should redirect_to(track_types_url)
    end
  end

end
