require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UpgradeGroupsController do

  def mock_upgrade_group(stubs={})
    @mock_upgrade_group ||= mock_model(UpgradeGroup, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all upgrade_groups as @upgrade_groups" do
      UpgradeGroup.stub(:all) { [mock_upgrade_group] }
      get :index
      assigns(:upgrade_groups).should eq([mock_upgrade_group])
    end
  end

  describe "GET show" do
    it "assigns the requested upgrade_group as @upgrade_group" do
      UpgradeGroup.stub(:find).with("37") { mock_upgrade_group }
      get :show, :id => "37"
      assigns(:upgrade_group).should be(mock_upgrade_group)
    end
  end

  describe "GET new" do
    it "assigns a new upgrade_group as @upgrade_group" do
      UpgradeGroup.stub(:new) { mock_upgrade_group }
      get :new
      assigns(:upgrade_group).should be(mock_upgrade_group)
    end
  end

  describe "GET edit" do
    it "assigns the requested upgrade_group as @upgrade_group" do
      UpgradeGroup.stub(:find).with("37") { mock_upgrade_group }
      get :edit, :id => "37"
      assigns(:upgrade_group).should be(mock_upgrade_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created upgrade_group as @upgrade_group" do
        UpgradeGroup.stub(:new).with({'these' => 'params'}) { mock_upgrade_group(:save => true) }
        post :create, :upgrade_group => {'these' => 'params'}
        assigns(:upgrade_group).should be(mock_upgrade_group)
      end

      it "redirects to the created upgrade_group" do
        UpgradeGroup.stub(:new) { mock_upgrade_group(:save => true) }
        post :create, :upgrade_group => {}
        response.should redirect_to(upgrade_group_url(mock_upgrade_group))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved upgrade_group as @upgrade_group" do
        UpgradeGroup.stub(:new).with({'these' => 'params'}) { mock_upgrade_group(:save => false) }
        post :create, :upgrade_group => {'these' => 'params'}
        assigns(:upgrade_group).should be(mock_upgrade_group)
      end

      it "re-renders the 'new' template" do
        UpgradeGroup.stub(:new) { mock_upgrade_group(:save => false) }
        post :create, :upgrade_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested upgrade_group" do
        UpgradeGroup.stub(:find).with("37") { mock_upgrade_group }
        mock_upgrade_group.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :upgrade_group => {'these' => 'params'}
      end

      it "assigns the requested upgrade_group as @upgrade_group" do
        UpgradeGroup.stub(:find) { mock_upgrade_group(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:upgrade_group).should be(mock_upgrade_group)
      end

      it "redirects to the upgrade_group" do
        UpgradeGroup.stub(:find) { mock_upgrade_group(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(upgrade_group_url(mock_upgrade_group))
      end
    end

    describe "with invalid params" do
      it "assigns the upgrade_group as @upgrade_group" do
        UpgradeGroup.stub(:find) { mock_upgrade_group(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:upgrade_group).should be(mock_upgrade_group)
      end

      it "re-renders the 'edit' template" do
        UpgradeGroup.stub(:find) { mock_upgrade_group(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested upgrade_group" do
      UpgradeGroup.stub(:find).with("37") { mock_upgrade_group }
      mock_upgrade_group.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the upgrade_groups list" do
      UpgradeGroup.stub(:find) { mock_upgrade_group }
      delete :destroy, :id => "1"
      response.should redirect_to(upgrade_groups_url)
    end
  end

end
